### ISSUE TITLE
If mpd is killed, mpDris2 attempts to connect every second

### ISSUE THREAD

**Issue by i30817** [eonpatapon/mpDris2#120]
From journalctl, every second.
It's not a systemd service i think, i did

`systemctl stop --user mpDris2.service` and `systemctl stop mpDris2.service`, with no effect (though indeed there was a --user service enabled but already dead, to autostart it i think). Rather it's mpdris2 insisting on attempting to connect to the broken socket.

jun 21 12:06:00 AIVAS mpdris2.desktop[1604]: 2019-06-21 12:06:00,644 base INFO: Calling MPD connect('/home/i30817/.config/mpd/socket', 6600, timeout=None)

btw, i didn't know that pgrep can't find the actual app name instead of python3 yet. Any way to fix that or it's just a question of waiting for distros?

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
Same issue here.

**Comment by fabianski7** [comment]
after two days with the mpd server deactivated, my log file became giant because of it.
up for 2020 and 2021 🤭🥳

**Comment by i30817** [comment]
I switched to mocp since i don't really need the server functionality. Just more convenient.

**Comment by xeruf** [comment]
Might be related to an issue of mine:
Recently, as I was reconfiguring MPD to use pipewire to stream via bluetooth, I noticed my fan spinning widly, and apparently mpdris2 was using one CPU core for 100% for a while, so that I force-killed it. No more details right now. If you have any advice how I can provide a better report if it happens again let me know.
Maybe because it tries to reconnect constantly?
